<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbFavoritos', 'doctrine');

/**
 * Base_TbFavoritos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_favorito
 * @property integer $sq_usuario
 * @property integer $sq_produto
 * @property boolean $st_ativo
 * @property TbUsuarios $TbUsuarios
 * @property TbProdutos $TbProdutos
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbFavoritos extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_favoritos');
        $this->hasColumn('sq_favorito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('sq_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '4',
             ));
        $this->hasColumn('sq_produto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '4',
             ));
        $this->hasColumn('st_ativo', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'true',
             'primary' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbUsuarios', array(
             'local' => 'sq_usuario',
             'foreign' => 'sq_usuario'));

        $this->hasOne('TbProdutos', array(
             'local' => 'sq_produto',
             'foreign' => 'sq_produto'));
    }
}