<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbHistorico', 'doctrine');

/**
 * Base_TbHistorico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_historico
 * @property integer $sq_atividade
 * @property integer $sq_usuario
 * @property integer $sq_pedido
 * @property date $dt_historico
 * @property boolean $st_ativo
 * @property TbUsuarios $TbUsuarios
 * @property TbPedidos $TbPedidos
 * @property TbAtividades $TbAtividades
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbHistorico extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_historico');
        $this->hasColumn('sq_historico', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             ));
        $this->hasColumn('sq_atividade', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('sq_usuario', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('sq_pedido', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('dt_historico', 'date', null, array(
             'type' => 'date',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('st_ativo', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbUsuarios', array(
             'local' => 'sq_usuario',
             'foreign' => 'sq_usuario'));

        $this->hasOne('TbPedidos', array(
             'local' => 'sq_pedido',
             'foreign' => 'sq_pedido'));

        $this->hasOne('TbAtividades', array(
             'local' => 'sq_atividade',
             'foreign' => 'sq_atividade'));
    }
}