<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbMunicipios', 'doctrine');

/**
 * Base_TbMunicipios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_municipio
 * @property integer $sq_uf
 * @property string $nm_municipio
 * @property boolean $st_ativo
 * @property TbUfs $TbUfs
 * @property Doctrine_Collection $TbUsuarios
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbMunicipios extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_municipios');
        $this->hasColumn('sq_municipio', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             ));
        $this->hasColumn('sq_uf', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('nm_municipio', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('st_ativo', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbUfs', array(
             'local' => 'sq_uf',
             'foreign' => 'sq_uf'));

        $this->hasMany('TbUsuarios', array(
             'local' => 'sq_municipio',
             'foreign' => 'sq_municipio'));
    }
}