<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbTelefones', 'doctrine');

/**
 * Base_TbTelefones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_telefone
 * @property string $tp_telefone
 * @property integer $sq_usuario
 * @property string $nu_telefone
 * @property string $nu_ddd
 * @property boolean $st_ativo
 * @property TbUsuarios $TbUsuarios
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbTelefones extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_telefones');
        $this->hasColumn('sq_telefone', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('tp_telefone', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sq_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '4',
             ));
        $this->hasColumn('nu_telefone', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nu_ddd', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('st_ativo', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'true',
             'primary' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbUsuarios', array(
             'local' => 'sq_usuario',
             'foreign' => 'sq_usuario'));
    }
}