<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbTpTelefones', 'doctrine');

/**
 * Base_TbTpTelefones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_tp_telefone
 * @property string $tx_tp_telefone
 * @property boolean $st_ativo
 * @property Doctrine_Collection $TbTelefones
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbTpTelefones extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_tp_telefones');
        $this->hasColumn('sq_tp_telefone', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             ));
        $this->hasColumn('tx_tp_telefone', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('st_ativo', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbTelefones', array(
             'local' => 'sq_tp_telefone',
             'foreign' => 'sq_tp_telefone'));
    }
}