<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbUsuarios', 'doctrine');

/**
 * Base_TbUsuarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_usuario
 * @property integer $sq_municipio
 * @property integer $sq_perfil
 * @property string $nm_usuario
 * @property string $nu_cpf
 * @property string $tx_senha
 * @property string $tx_email
 * @property string $tx_endereco
 * @property string $nu_cep
 * @property boolean $st_ativo
 * @property TbMunicipios $TbMunicipios
 * @property TbPerfil $TbPerfil
 * @property Doctrine_Collection $TbFavoritos
 * @property Doctrine_Collection $TbHistorico
 * @property Doctrine_Collection $TbPedidos
 * @property Doctrine_Collection $TbTelefonesUsuarios
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbUsuarios extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_usuarios');
        $this->hasColumn('sq_usuario', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             ));
        $this->hasColumn('sq_municipio', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('sq_perfil', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('nm_usuario', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('nu_cpf', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('tx_senha', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('tx_email', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('tx_endereco', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('nu_cep', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('st_ativo', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbMunicipios', array(
             'local' => 'sq_municipio',
             'foreign' => 'sq_municipio'));

        $this->hasOne('TbPerfil', array(
             'local' => 'sq_perfil',
             'foreign' => 'sq_perfil'));

        $this->hasMany('TbFavoritos', array(
             'local' => 'sq_usuario',
             'foreign' => 'sq_usuario'));

        $this->hasMany('TbHistorico', array(
             'local' => 'sq_usuario',
             'foreign' => 'sq_usuario'));

        $this->hasMany('TbPedidos', array(
             'local' => 'sq_usuario',
             'foreign' => 'sq_usuario'));

        $this->hasMany('TbTelefonesUsuarios', array(
             'local' => 'sq_usuario',
             'foreign' => 'sq_usuario'));
    }
}