<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headScript();
        ?>

        <script type="text/javascript" language="javascript" src="/camisetas/public/extjs/examples/ux/ProgressBarPager.js"></script>
        <script type="text/javascript" language="javascript" src="/camisetas/public/extjs/examples/ux/statusbar/StatusBar.js"></script>
        <script type="text/javascript" src="/camisetas/application/modules/default/views/layouts/<?php echo $this->controller; ?>/layout.js"></script>
        <script type="text/javascript" src="/camisetas/public/extjs/examples/ux/IconComboBox.js"></script>
        <script type="text/javascript" src="/camisetas/public/extjs/examples/ux/RowEditor.js"></script>
        <script type="text/javascript" src="/camisetas/public/extjs/examples/ux/Spinner.js"></script>
        <script type="text/javascript" src="/camisetas/public/extjs/examples/ux/SpinnerField.js"></script>

        <script type="text/javascript" src="/camisetas/outros/png-1.0/vtypes.js"></script>
        <script type="text/javascript" src="/camisetas/outros/png-1.0/upload.js"></script>
        <script type="text/javascript" src="/camisetas/outros/png-1.0/js/jquery.min.js"></script>

        <script type="text/javascript" src="/camisetas/outros/png-1.0/resolucao.js"></script>
        <script type="text/javascript" src="/camisetas/outros/png-1.0/introducao.js"></script>

        <script type="text/javascript" src="/camisetas/public/extjs/examples/view/multisort-dataview.js"></script>
    </head>
    <body>
        <div id="introducao"><div id="marca-intro"></div><div id="loader"><p>Carregando...</p></div></div>
        <script type="text/javascript" language="javascript" >
            Ext.onReady(function(){
                try{
                    new App.Default.Layout.Cliente;
                    Ext.get('introducao').fadeOut(100);
                }catch(e){
                    alert('Ocorreu um erro fatal!\n['+e+']');
                }
            });
        </script>
    </body>
</html>