<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpespessoaendereco extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('pes_pessoa_endereco', array(
             'sq_pessoa_endereco' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_pessoa' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
             ),
             'sq_endereco' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_pessoa_endereco',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('pes_pessoa_endereco');
    }
}