<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpespessoadocumento extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('pes_pessoa_documento', array(
             'sq_pessoa_documento' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_documento_tipo' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'sg_uf' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'sq_pessoa' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'ds_numero_documento' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ds_orgao_emissor' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'cd_pais' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'dt_emissao' => 
             array(
              'type' => 'date',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => 25,
             ),
             'dt_validade' => 
             array(
              'type' => 'date',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => 25,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_pessoa_documento',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('pes_pessoa_documento');
    }
}