<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addspesitfuncional extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('spe_sit_funcional', array(
             'cd_sit_funcional' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'primary' => true,
              'length' => NULL,
             ),
             'ds_sit_funcional' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'cd_sit_funcional',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('spe_sit_funcional');
    }
}