<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addgeoregiao extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('geo_regiao', array(
             'sq_regiao' => 
             array(
              'type' => 'integer',
              'length' => 2,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'nm_regiao' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_regiao',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('geo_regiao');
    }
}