<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addgeomunicipio extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('geo_municipio', array(
             'sq_municipio' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'cd_ibge' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => NULL,
             ),
             'sg_uf' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'nm_municipio' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'nu_lon' => 
             array(
              'type' => 'decimal',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => 18,
             ),
             'nu_lat' => 
             array(
              'type' => 'decimal',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => 18,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_municipio',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('geo_municipio');
    }
}