<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addconperfilestrutura extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('con_perfil_estrutura', array(
             'sq_perfil_unid_organiz' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_perfil' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'sq_estrutura' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_perfil_unid_organiz',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('con_perfil_estrutura');
    }
}