<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddocresposta extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('doc_resposta', array(
             'sq_resposta' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_doc_tipo' => 
             array(
              'type' => 'integer',
              'length' => 2,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'sq_tramite' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_resposta',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('doc_resposta');
    }
}