<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addinsprofsenha extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ins_prof_senha', array(
             'sq_prof_senha' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_profissional' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'ds_prof_senha' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_prof_senha',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ins_prof_senha');
    }
}