<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddocdigital extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('doc_digital', array(
             'sq_digital' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'ds_digital' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'nu_lote' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_digital',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('doc_digital');
    }
}