<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddocdocumento extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('doc_documento', array(
             'sq_digital' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_doc_tipo' => 
             array(
              'type' => 'integer',
              'length' => 2,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'sq_classificacao' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'dt_doc_prazo' => 
             array(
              'type' => 'timestamp',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => 25,
             ),
             'tp_acesso' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'default' => '\'R\'::bpchar',
              'primary' => false,
              'length' => NULL,
             ),
             'fg_doc_sem_numero' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'false',
              'primary' => false,
             ),
             'ds_num_documento' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => NULL,
             ),
             'tp_procedencia' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ds_origem_nome' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ts_ds_origem_nome' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'sq_origem_unid_organiz' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
             ),
             'dt_documento' => 
             array(
              'type' => 'timestamp',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => 25,
             ),
             'tp_destino' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'sq_destino_unid_organiz' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
             ),
             'sq_doc_classificacao' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
             ),
             'ds_destino_nome' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ts_destino_nome' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ds_encaminhado_para' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ts_encaminhado_para' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ds_nom_sofre_acao' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => NULL,
             ),
             'ts_nom_sofre_acao' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => NULL,
             ),
             'ds_nom_assinatura' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ts_nom_assinatura' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ds_cargo_assinatura' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'ts_cargo_assinatura' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_digital',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('doc_documento');
    }
}