<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddoctipoenvio extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('doc_tipo_envio', array(
             'cd_opcao_envio' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'primary' => true,
              'length' => NULL,
             ),
             'cd_opcao_envio_pai' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => NULL,
             ),
             'ds_opcao_envio' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'cd_opcao_envio',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('doc_tipo_envio');
    }
}