<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbAtividades', 'doctrine');

/**
 * Base_TbAtividades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_atividade
 * @property string $tx_atividade
 * @property boolean $st_ativo
 * @property Doctrine_Collection $TbHistorico
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbAtividades extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_atividades');
        $this->hasColumn('sq_atividade', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             ));
        $this->hasColumn('tx_atividade', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('st_ativo', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbHistorico', array(
             'local' => 'sq_atividade',
             'foreign' => 'sq_atividade'));
    }
}