<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbProdutosPedidos', 'doctrine');

/**
 * Base_TbProdutosPedidos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_produto_pedido
 * @property integer $sq_pedido
 * @property integer $sq_produto
 * @property TbPedidos $TbPedidos
 * @property TbProdutos $TbProdutos
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbProdutosPedidos extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_produtos_pedidos');
        $this->hasColumn('sq_produto_pedido', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             ));
        $this->hasColumn('sq_pedido', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('sq_produto', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbPedidos', array(
             'local' => 'sq_pedido',
             'foreign' => 'sq_pedido'));

        $this->hasOne('TbProdutos', array(
             'local' => 'sq_produto',
             'foreign' => 'sq_produto'));
    }
}