<?php

// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbProdutoPedido', 'doctrine');

/**
 * Base_TbProdutoPedido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_produto_pedido
 * @property integer $sq_pedido
 * @property integer $sq_produto
 * @property boolean $st_ativo
 * @property integer $nu_quantidade
 * @property TbPedidos $TbPedidos
 * @property TbProdutos $TbProdutos
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbProdutoPedido extends Doctrine_Record {

    public function setTableDefinition() {
        $this->setTableName('tb_produto_pedido');
        $this->hasColumn('sq_produto_pedido', 'integer', 4, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => true,
            'autoincrement' => true,
            'length' => '4',
        ));
        $this->hasColumn('sq_pedido', 'integer', 4, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'notnull' => true,
            'primary' => false,
            'length' => '4',
        ));
        $this->hasColumn('sq_produto', 'integer', 4, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'notnull' => true,
            'primary' => false,
            'length' => '4',
        ));
        $this->hasColumn('st_ativo', 'boolean', 1, array(
            'type' => 'boolean',
            'fixed' => 0,
            'unsigned' => false,
            'notnull' => true,
            'default' => 'true',
            'primary' => false,
            'length' => '1',
        ));
        $this->hasColumn('nu_quantidade', 'integer', 4, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'notnull' => true,
            'primary' => false,
            'length' => '4',
        ));
    }

    public function setUp() {
        parent::setUp();
        $this->hasOne('TbPedidos', array(
            'local' => 'sq_pedido',
            'foreign' => 'sq_pedido'));

        $this->hasOne('TbProdutos', array(
            'local' => 'sq_produto',
            'foreign' => 'sq_produto'));
    }

}