<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbTelefonesUsuarios', 'doctrine');

/**
 * Base_TbTelefonesUsuarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sq_telefone_usuario
 * @property integer $sq_usuario
 * @property integer $sq_telefone
 * @property TbUsuarios $TbUsuarios
 * @property TbTelefones $TbTelefones
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_TbTelefonesUsuarios extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_telefones_usuarios');
        $this->hasColumn('sq_telefone_usuario', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             ));
        $this->hasColumn('sq_usuario', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('sq_telefone', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbUsuarios', array(
             'local' => 'sq_usuario',
             'foreign' => 'sq_usuario'));

        $this->hasOne('TbTelefones', array(
             'local' => 'sq_telefone',
             'foreign' => 'sq_telefone'));
    }
}