<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddocacompanhar extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('doc_acompanhar', array(
             'sq_acompanhar' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_digital_op' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'dt_inicio' => 
             array(
              'type' => 'timestamp',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => 25,
             ),
             'dt_termino' => 
             array(
              'type' => 'timestamp',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_acompanhar',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('doc_acompanhar');
    }
}