<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addspeuorg extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('spe_uorg', array(
             'cd_uorg' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'primary' => true,
              'length' => NULL,
             ),
             'nm_uorg' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'cd_uorg',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('spe_uorg');
    }
}