<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddocprazo extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('doc_prazo', array(
             'sq_prazo' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_digital_op' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'dt_prazo' => 
             array(
              'type' => 'timestamp',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_prazo',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('doc_prazo');
    }
}