<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addspegrupocargoemprego extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('spe_grupo_cargo_emprego', array(
             'cd_grup_carg_emprego' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'primary' => true,
              'length' => NULL,
             ),
             'ds_grup_carg_emprego' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'cd_grup_carg_emprego',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('spe_grupo_cargo_emprego');
    }
}