<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('con_controller', 'con_controller_sq_sistema_con_sistema_sq_sistema', array(
             'name' => 'con_controller_sq_sistema_con_sistema_sq_sistema',
             'local' => 'sq_sistema',
             'foreign' => 'sq_sistema',
             'foreignTable' => 'con_sistema',
             ));
        $this->createForeignKey('con_layout', 'con_layout_sq_idioma_layout_con_idioma_layout_sq_idioma_layout', array(
             'name' => 'con_layout_sq_idioma_layout_con_idioma_layout_sq_idioma_layout',
             'local' => 'sq_idioma_layout',
             'foreign' => 'sq_idioma_layout',
             'foreignTable' => 'con_idioma_layout',
             ));
        $this->createForeignKey('con_layout', 'con_layout_sq_sistema_con_sistema_sq_sistema', array(
             'name' => 'con_layout_sq_sistema_con_sistema_sq_sistema',
             'local' => 'sq_sistema',
             'foreign' => 'sq_sistema',
             'foreignTable' => 'con_sistema',
             ));
        $this->createForeignKey('con_layout', 'con_layout_sq_tema_layout_con_tema_layout_sq_tema_layout', array(
             'name' => 'con_layout_sq_tema_layout_con_tema_layout_sq_tema_layout',
             'local' => 'sq_tema_layout',
             'foreign' => 'sq_tema_layout',
             'foreignTable' => 'con_tema_layout',
             ));
        $this->createForeignKey('con_layout', 'con_layout_sq_profissional_ins_profissional_sq_profissional', array(
             'name' => 'con_layout_sq_profissional_ins_profissional_sq_profissional',
             'local' => 'sq_profissional',
             'foreign' => 'sq_profissional',
             'foreignTable' => 'ins_profissional',
             ));
        $this->createForeignKey('con_log', 'con_log_sq_profissional_ins_profissional_sq_profissional', array(
             'name' => 'con_log_sq_profissional_ins_profissional_sq_profissional',
             'local' => 'sq_profissional',
             'foreign' => 'sq_profissional',
             'foreignTable' => 'ins_profissional',
             ));
        $this->createForeignKey('con_menu', 'con_menu_sq_conteiner_con_conteiner_sq_conteiner', array(
             'name' => 'con_menu_sq_conteiner_con_conteiner_sq_conteiner',
             'local' => 'sq_conteiner',
             'foreign' => 'sq_conteiner',
             'foreignTable' => 'con_conteiner',
             ));
        $this->createForeignKey('con_menu_profissional', 'con_menu_profissional_sq_menu_con_menu_sq_menu', array(
             'name' => 'con_menu_profissional_sq_menu_con_menu_sq_menu',
             'local' => 'sq_menu',
             'foreign' => 'sq_menu',
             'foreignTable' => 'con_menu',
             ));
        $this->createForeignKey('con_menu_profissional', 'csis', array(
             'name' => 'csis',
             'local' => 'sq_profissional',
             'foreign' => 'sq_profissional',
             'foreignTable' => 'ins_profissional',
             ));
        $this->createForeignKey('con_perfil_estrutura', 'con_perfil_estrutura_sq_perfil_con_perfil_sq_perfil', array(
             'name' => 'con_perfil_estrutura_sq_perfil_con_perfil_sq_perfil',
             'local' => 'sq_perfil',
             'foreign' => 'sq_perfil',
             'foreignTable' => 'con_perfil',
             ));
        $this->createForeignKey('con_perfil_menu', 'con_perfil_menu_sq_menu_con_menu_sq_menu', array(
             'name' => 'con_perfil_menu_sq_menu_con_menu_sq_menu',
             'local' => 'sq_menu',
             'foreign' => 'sq_menu',
             'foreignTable' => 'con_menu',
             ));
        $this->createForeignKey('con_perfil_menu', 'con_perfil_menu_sq_perfil_con_perfil_sq_perfil', array(
             'name' => 'con_perfil_menu_sq_perfil_con_perfil_sq_perfil',
             'local' => 'sq_perfil',
             'foreign' => 'sq_perfil',
             'foreignTable' => 'con_perfil',
             ));
        $this->createForeignKey('doc_acompanhar', 'doc_acompanhar_sq_digital_op_doc_digital_op_sq_digital_op', array(
             'name' => 'doc_acompanhar_sq_digital_op_doc_digital_op_sq_digital_op',
             'local' => 'sq_digital_op',
             'foreign' => 'sq_digital_op',
             'foreignTable' => 'doc_digital_op',
             ));
        $this->createForeignKey('doc_ass_sinonimo', 'dsds', array(
             'name' => 'dsds',
             'local' => 'sq_classif_sinonimo',
             'foreign' => 'sq_classificacao',
             'foreignTable' => 'doc_classificacao',
             ));
        $this->createForeignKey('doc_ass_sinonimo', 'dsds_1', array(
             'name' => 'dsds_1',
             'local' => 'sq_classificacao',
             'foreign' => 'sq_classificacao',
             'foreignTable' => 'doc_classificacao',
             ));
        $this->createForeignKey('doc_classificacao', 'dsds_2', array(
             'name' => 'dsds_2',
             'local' => 'sq_grp_atividade',
             'foreign' => 'sq_grp_atividade',
             'foreignTable' => 'doc_grp_atividade',
             ));
        $this->createForeignKey('doc_comentario', 'doc_comentario_sq_digital_op_doc_digital_op_sq_digital_op', array(
             'name' => 'doc_comentario_sq_digital_op_doc_digital_op_sq_digital_op',
             'local' => 'sq_digital_op',
             'foreign' => 'sq_digital_op',
             'foreignTable' => 'doc_digital_op',
             ));
        $this->createForeignKey('doc_delegacao', 'doc_delegacao_sq_operacao_doc_operacao_sq_operacao', array(
             'name' => 'doc_delegacao_sq_operacao_doc_operacao_sq_operacao',
             'local' => 'sq_operacao',
             'foreign' => 'sq_operacao',
             'foreignTable' => 'doc_operacao',
             ));
        $this->createForeignKey('doc_delegacao', 'doc_delegacao_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz', array(
             'name' => 'doc_delegacao_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz',
             'local' => 'sq_unid_organiz',
             'foreign' => 'sq_unid_organiz',
             'foreignTable' => 'ins_unid_organiz',
             ));
        $this->createForeignKey('doc_delegacao', 'dsps', array(
             'name' => 'dsps',
             'local' => 'sq_pessoa_fisica',
             'foreign' => 'sq_pessoa_fisica',
             'foreignTable' => 'pes_pessoa_fisica',
             ));
        $this->createForeignKey('doc_despacho', 'doc_despacho_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz', array(
             'name' => 'doc_despacho_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz',
             'local' => 'sq_unid_organiz',
             'foreign' => 'sq_unid_organiz',
             'foreignTable' => 'ins_unid_organiz',
             ));
        $this->createForeignKey('doc_despacho', 'doc_despacho_sq_pessoa_fisica_pes_pessoa_fisica_sq_pessoa_fisica', array(
             'name' => 'doc_despacho_sq_pessoa_fisica_pes_pessoa_fisica_sq_pessoa_fisica',
             'local' => 'sq_pessoa_fisica',
             'foreign' => 'sq_pessoa_fisica',
             'foreignTable' => 'pes_pessoa_fisica',
             ));
        $this->createForeignKey('doc_digital_op', 'doc_digital_op_sq_delegacao_doc_delegacao_sq_delegacao', array(
             'name' => 'doc_digital_op_sq_delegacao_doc_delegacao_sq_delegacao',
             'local' => 'sq_delegacao',
             'foreign' => 'sq_delegacao',
             'foreignTable' => 'doc_delegacao',
             ));
        $this->createForeignKey('doc_digital_op', 'doc_digital_op_sq_digital_doc_digital_sq_digital', array(
             'name' => 'doc_digital_op_sq_digital_doc_digital_sq_digital',
             'local' => 'sq_digital',
             'foreign' => 'sq_digital',
             'foreignTable' => 'doc_digital',
             ));
        $this->createForeignKey('doc_digital_op', 'doc_digital_op_sq_digital_pai_doc_documento_sq_digital', array(
             'name' => 'doc_digital_op_sq_digital_pai_doc_documento_sq_digital',
             'local' => 'sq_digital_pai',
             'foreign' => 'sq_digital',
             'foreignTable' => 'doc_documento',
             ));
        $this->createForeignKey('doc_digital_op', 'doc_digital_op_sq_operacao_doc_operacao_sq_operacao', array(
             'name' => 'doc_digital_op_sq_operacao_doc_operacao_sq_operacao',
             'local' => 'sq_operacao',
             'foreign' => 'sq_operacao',
             'foreignTable' => 'doc_operacao',
             ));
        $this->createForeignKey('doc_digital_op', 'doc_digital_op_sq_prioridade_doc_prioridade_sq_prioridade', array(
             'name' => 'doc_digital_op_sq_prioridade_doc_prioridade_sq_prioridade',
             'local' => 'sq_prioridade',
             'foreign' => 'sq_prioridade',
             'foreignTable' => 'doc_prioridade',
             ));
        $this->createForeignKey('doc_digital_op', 'doc_digital_op_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz', array(
             'name' => 'doc_digital_op_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz',
             'local' => 'sq_unid_organiz',
             'foreign' => 'sq_unid_organiz',
             'foreignTable' => 'ins_unid_organiz',
             ));
        $this->createForeignKey('doc_digital_op', 'dsps_1', array(
             'name' => 'dsps_1',
             'local' => 'sq_pessoa_fisica',
             'foreign' => 'sq_pessoa_fisica',
             'foreignTable' => 'pes_pessoa_fisica',
             ));
        $this->createForeignKey('doc_documento', 'dsds_6', array(
             'name' => 'dsds_6',
             'local' => 'sq_classificacao',
             'foreign' => 'sq_classificacao',
             'foreignTable' => 'doc_classificacao',
             ));
        $this->createForeignKey('doc_documento', 'doc_documento_sq_doc_tipo_doc_tipo_sq_doc_tipo', array(
             'name' => 'doc_documento_sq_doc_tipo_doc_tipo_sq_doc_tipo',
             'local' => 'sq_doc_tipo',
             'foreign' => 'sq_doc_tipo',
             'foreignTable' => 'doc_tipo',
             ));
        $this->createForeignKey('doc_grp_tram_organiz', 'dsds_8', array(
             'name' => 'dsds_8',
             'local' => 'sq_grupo_tramite',
             'foreign' => 'sq_grupo_tramite',
             'foreignTable' => 'doc_grup_tramite',
             ));
        $this->createForeignKey('doc_grp_tram_organiz', 'dsis', array(
             'name' => 'dsis',
             'local' => 'sq_unid_organiz',
             'foreign' => 'sq_unid_organiz',
             'foreignTable' => 'ins_unid_organiz',
             ));
        $this->createForeignKey('doc_imagem', 'doc_imagem_sq_digital_op_doc_digital_op_sq_digital_op', array(
             'name' => 'doc_imagem_sq_digital_op_doc_digital_op_sq_digital_op',
             'local' => 'sq_digital_op',
             'foreign' => 'sq_digital_op',
             'foreignTable' => 'doc_digital_op',
             ));
        $this->createForeignKey('doc_prazo', 'doc_prazo_sq_digital_op_doc_digital_op_sq_digital_op', array(
             'name' => 'doc_prazo_sq_digital_op_doc_digital_op_sq_digital_op',
             'local' => 'sq_digital_op',
             'foreign' => 'sq_digital_op',
             'foreignTable' => 'doc_digital_op',
             ));
        $this->createForeignKey('doc_resposta', 'doc_resposta_sq_doc_tipo_doc_tipo_sq_doc_tipo', array(
             'name' => 'doc_resposta_sq_doc_tipo_doc_tipo_sq_doc_tipo',
             'local' => 'sq_doc_tipo',
             'foreign' => 'sq_doc_tipo',
             'foreignTable' => 'doc_tipo',
             ));
        $this->createForeignKey('doc_resposta', 'doc_resposta_sq_tramite_doc_tramite_sq_tramite', array(
             'name' => 'doc_resposta_sq_tramite_doc_tramite_sq_tramite',
             'local' => 'sq_tramite',
             'foreign' => 'sq_tramite',
             'foreignTable' => 'doc_tramite',
             ));
        $this->createForeignKey('doc_tramite', 'doc_tramite_sq_despacho_doc_despacho_sq_despacho', array(
             'name' => 'doc_tramite_sq_despacho_doc_despacho_sq_despacho',
             'local' => 'sq_despacho',
             'foreign' => 'sq_despacho',
             'foreignTable' => 'doc_despacho',
             ));
        $this->createForeignKey('doc_tramite', 'doc_tramite_sq_digital_op_doc_digital_op_sq_digital_op', array(
             'name' => 'doc_tramite_sq_digital_op_doc_digital_op_sq_digital_op',
             'local' => 'sq_digital_op',
             'foreign' => 'sq_digital_op',
             'foreignTable' => 'doc_digital_op',
             ));
        $this->createForeignKey('doc_tramite', 'doc_tramite_sq_malote_doc_malote_sq_malote', array(
             'name' => 'doc_tramite_sq_malote_doc_malote_sq_malote',
             'local' => 'sq_malote',
             'foreign' => 'sq_malote',
             'foreignTable' => 'doc_malote',
             ));
        $this->createForeignKey('doc_tramite', 'doc_tramite_cd_opcao_envio_doc_tipo_envio_cd_opcao_envio', array(
             'name' => 'doc_tramite_cd_opcao_envio_doc_tipo_envio_cd_opcao_envio',
             'local' => 'cd_opcao_envio',
             'foreign' => 'cd_opcao_envio',
             'foreignTable' => 'doc_tipo_envio',
             ));
        $this->createForeignKey('doc_tramite', 'doc_tramite_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz', array(
             'name' => 'doc_tramite_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz',
             'local' => 'sq_unid_organiz',
             'foreign' => 'sq_unid_organiz',
             'foreignTable' => 'ins_unid_organiz',
             ));
        $this->createForeignKey('doc_tramite', 'doc_tramite_sq_pessoa_fisica_pes_pessoa_fisica_sq_pessoa_fisica', array(
             'name' => 'doc_tramite_sq_pessoa_fisica_pes_pessoa_fisica_sq_pessoa_fisica',
             'local' => 'sq_pessoa_fisica',
             'foreign' => 'sq_pessoa_fisica',
             'foreignTable' => 'pes_pessoa_fisica',
             ));
        $this->createForeignKey('doc_tramite_organiz', 'dsds_11', array(
             'name' => 'dsds_11',
             'local' => 'sq_grupo_tramite',
             'foreign' => 'sq_grupo_tramite',
             'foreignTable' => 'doc_grup_tramite',
             ));
        $this->createForeignKey('doc_tramite_organiz', 'dsis_1', array(
             'name' => 'dsis_1',
             'local' => 'sq_unid_organiz',
             'foreign' => 'sq_unid_organiz',
             'foreignTable' => 'ins_unid_organiz',
             ));
        $this->createForeignKey('geo_municipio', 'geo_municipio_sg_uf_geo_uf_sg_uf', array(
             'name' => 'geo_municipio_sg_uf_geo_uf_sg_uf',
             'local' => 'sg_uf',
             'foreign' => 'sg_uf',
             'foreignTable' => 'geo_uf',
             ));
        $this->createForeignKey('geo_uf', 'geo_uf_sq_regiao_geo_regiao_sq_regiao', array(
             'name' => 'geo_uf_sq_regiao_geo_regiao_sq_regiao',
             'local' => 'sq_regiao',
             'foreign' => 'sq_regiao',
             'foreignTable' => 'geo_regiao',
             ));
        $this->createForeignKey('ger_endereco', 'ger_endereco_sq_municipio_geo_municipio_sq_municipio', array(
             'name' => 'ger_endereco_sq_municipio_geo_municipio_sq_municipio',
             'local' => 'sq_municipio',
             'foreign' => 'sq_municipio',
             'foreignTable' => 'geo_municipio',
             ));
        $this->createForeignKey('ger_endereco', 'ger_endereco_cd_pais_geo_pais_cd_pais', array(
             'name' => 'ger_endereco_cd_pais_geo_pais_cd_pais',
             'local' => 'cd_pais',
             'foreign' => 'cd_pais',
             'foreignTable' => 'geo_pais',
             ));
        $this->createForeignKey('ger_telefone', 'ger_telefone_cd_pais_geo_pais_cd_pais', array(
             'name' => 'ger_telefone_cd_pais_geo_pais_cd_pais',
             'local' => 'cd_pais',
             'foreign' => 'cd_pais',
             'foreignTable' => 'geo_pais',
             ));
        $this->createForeignKey('ger_telefone', 'ger_telefone_sq_tel_tipo_ger_tel_tipo_sq_tel_tipo', array(
             'name' => 'ger_telefone_sq_tel_tipo_ger_tel_tipo_sq_tel_tipo',
             'local' => 'sq_tel_tipo',
             'foreign' => 'sq_tel_tipo',
             'foreignTable' => 'ger_tel_tipo',
             ));
        $this->createForeignKey('ins_doc_legal', 'isis', array(
             'name' => 'isis',
             'local' => 'sq_doc_legal_tipo',
             'foreign' => 'sq_doc_legal_tipo',
             'foreignTable' => 'ins_doc_legal_tipo',
             ));
        $this->createForeignKey('ins_doc_legal', 'ins_doc_legal_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz', array(
             'name' => 'ins_doc_legal_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz',
             'local' => 'sq_unid_organiz',
             'foreign' => 'sq_unid_organiz',
             'foreignTable' => 'ins_unid_organiz',
             ));
        $this->createForeignKey('ins_endereco_estrutura', 'ins_endereco_estrutura_sq_endereco_ger_endereco_sq_endereco', array(
             'name' => 'ins_endereco_estrutura_sq_endereco_ger_endereco_sq_endereco',
             'local' => 'sq_endereco',
             'foreign' => 'sq_endereco',
             'foreignTable' => 'ger_endereco',
             ));
        $this->createForeignKey('ins_endereco_estrutura', 'ins_endereco_estrutura_sq_estrutura_ins_estrutura_sq_estrutura', array(
             'name' => 'ins_endereco_estrutura_sq_estrutura_ins_estrutura_sq_estrutura',
             'local' => 'sq_estrutura',
             'foreign' => 'sq_estrutura',
             'foreignTable' => 'ins_estrutura',
             ));
        $this->createForeignKey('ins_estrutura', 'ins_estrutura_sq_tipo_estrut_ins_tipo_estrut_sq_tipo_estrut', array(
             'name' => 'ins_estrutura_sq_tipo_estrut_ins_tipo_estrut_sq_tipo_estrut',
             'local' => 'sq_tipo_estrut',
             'foreign' => 'sq_tipo_estrut',
             'foreignTable' => 'ins_tipo_estrut',
             ));
        $this->createForeignKey('ins_estrutura', 'ins_estrutura_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz', array(
             'name' => 'ins_estrutura_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz',
             'local' => 'sq_unid_organiz',
             'foreign' => 'sq_unid_organiz',
             'foreignTable' => 'ins_unid_organiz',
             ));
        $this->createForeignKey('ins_prof_lotacao', 'ins_prof_lotacao_sq_cat_cargo_ins_cat_cargo_sq_cat_cargo', array(
             'name' => 'ins_prof_lotacao_sq_cat_cargo_ins_cat_cargo_sq_cat_cargo',
             'local' => 'sq_cat_cargo',
             'foreign' => 'sq_cat_cargo',
             'foreignTable' => 'ins_cat_cargo',
             ));
        $this->createForeignKey('ins_prof_lotacao', 'ins_prof_lotacao_sq_estrutura_ins_estrutura_sq_estrutura', array(
             'name' => 'ins_prof_lotacao_sq_estrutura_ins_estrutura_sq_estrutura',
             'local' => 'sq_estrutura',
             'foreign' => 'sq_estrutura',
             'foreignTable' => 'ins_estrutura',
             ));
        $this->createForeignKey('ins_prof_lotacao', 'isis_2', array(
             'name' => 'isis_2',
             'local' => 'sq_profissional',
             'foreign' => 'sq_profissional',
             'foreignTable' => 'ins_profissional',
             ));
        $this->createForeignKey('ins_prof_senha', 'ins_prof_senha_sq_profissional_ins_profissional_sq_profissional', array(
             'name' => 'ins_prof_senha_sq_profissional_ins_profissional_sq_profissional',
             'local' => 'sq_profissional',
             'foreign' => 'sq_profissional',
             'foreignTable' => 'ins_profissional',
             ));
        $this->createForeignKey('ins_profissional', 'ins_profissional_sq_prof_tipo_ins_prof_tipo_sq_prof_tipo', array(
             'name' => 'ins_profissional_sq_prof_tipo_ins_prof_tipo_sq_prof_tipo',
             'local' => 'sq_prof_tipo',
             'foreign' => 'sq_prof_tipo',
             'foreignTable' => 'ins_prof_tipo',
             ));
        $this->createForeignKey('ins_profissional', 'ins_profissional_cd_matricula_spe_servidor_cd_matricula', array(
             'name' => 'ins_profissional_cd_matricula_spe_servidor_cd_matricula',
             'local' => 'cd_matricula',
             'foreign' => 'cd_matricula',
             'foreignTable' => 'spe_servidor',
             ));
        $this->createForeignKey('ins_tel_estrutura', 'ins_tel_estrutura_sq_telefone_ger_telefone_sq_telefone', array(
             'name' => 'ins_tel_estrutura_sq_telefone_ger_telefone_sq_telefone',
             'local' => 'sq_telefone',
             'foreign' => 'sq_telefone',
             'foreignTable' => 'ger_telefone',
             ));
        $this->createForeignKey('ins_tel_estrutura', 'ins_tel_estrutura_sq_estrutura_ins_estrutura_sq_estrutura', array(
             'name' => 'ins_tel_estrutura_sq_estrutura_ins_estrutura_sq_estrutura',
             'local' => 'sq_estrutura',
             'foreign' => 'sq_estrutura',
             'foreignTable' => 'ins_estrutura',
             ));
        $this->createForeignKey('ins_unid_organiz', 'ins_unid_organiz_sq_unid_tipo_ins_unid_tipo_sq_unid_tipo', array(
             'name' => 'ins_unid_organiz_sq_unid_tipo_ins_unid_tipo_sq_unid_tipo',
             'local' => 'sq_unid_tipo',
             'foreign' => 'sq_unid_tipo',
             'foreignTable' => 'ins_unid_tipo',
             ));
        $this->createForeignKey('ins_unid_organiz', 'ins_unid_organiz_cd_uorg_spe_uorg_cd_uorg', array(
             'name' => 'ins_unid_organiz_cd_uorg_spe_uorg_cd_uorg',
             'local' => 'cd_uorg',
             'foreign' => 'cd_uorg',
             'foreignTable' => 'spe_uorg',
             ));
        $this->createForeignKey('ins_unid_organiz_municipio', 'isgs', array(
             'name' => 'isgs',
             'local' => 'sq_municipio',
             'foreign' => 'sq_municipio',
             'foreignTable' => 'geo_municipio',
             ));
        $this->createForeignKey('ins_unid_organiz_municipio', 'isis_5', array(
             'name' => 'isis_5',
             'local' => 'sq_unid_organiz',
             'foreign' => 'sq_unid_organiz',
             'foreignTable' => 'ins_unid_organiz',
             ));
        $this->createForeignKey('pes_documento_tipo', 'pes_documento_tipo_cd_tipo_pes_tipo_cd_tipo', array(
             'name' => 'pes_documento_tipo_cd_tipo_pes_tipo_cd_tipo',
             'local' => 'cd_tipo',
             'foreign' => 'cd_tipo',
             'foreignTable' => 'pes_tipo',
             ));
        $this->createForeignKey('pes_email_pessoa', 'pes_email_pessoa_sq_email_ger_email_sq_email', array(
             'name' => 'pes_email_pessoa_sq_email_ger_email_sq_email',
             'local' => 'sq_email',
             'foreign' => 'sq_email',
             'foreignTable' => 'ger_email',
             ));
        $this->createForeignKey('pes_email_pessoa', 'pes_email_pessoa_sq_pessoa_pes_pessoa_sq_pessoa', array(
             'name' => 'pes_email_pessoa_sq_pessoa_pes_pessoa_sq_pessoa',
             'local' => 'sq_pessoa',
             'foreign' => 'sq_pessoa',
             'foreignTable' => 'pes_pessoa',
             ));
        $this->createForeignKey('pes_pessoa', 'pes_pessoa_cd_pais_geo_pais_cd_pais', array(
             'name' => 'pes_pessoa_cd_pais_geo_pais_cd_pais',
             'local' => 'cd_pais',
             'foreign' => 'cd_pais',
             'foreignTable' => 'geo_pais',
             ));
        $this->createForeignKey('pes_pessoa', 'pes_pessoa_cd_tipo_pes_tipo_cd_tipo', array(
             'name' => 'pes_pessoa_cd_tipo_pes_tipo_cd_tipo',
             'local' => 'cd_tipo',
             'foreign' => 'cd_tipo',
             'foreignTable' => 'pes_tipo',
             ));
        $this->createForeignKey('pes_pessoa_documento', 'pes_pessoa_documento_sg_uf_geo_uf_sg_uf', array(
             'name' => 'pes_pessoa_documento_sg_uf_geo_uf_sg_uf',
             'local' => 'sg_uf',
             'foreign' => 'sg_uf',
             'foreignTable' => 'geo_uf',
             ));
        $this->createForeignKey('pes_pessoa_documento', 'psps_1', array(
             'name' => 'psps_1',
             'local' => 'sq_documento_tipo',
             'foreign' => 'sq_documento_tipo',
             'foreignTable' => 'pes_documento_tipo',
             ));
        $this->createForeignKey('pes_pessoa_documento', 'pes_pessoa_documento_sq_pessoa_pes_pessoa_sq_pessoa', array(
             'name' => 'pes_pessoa_documento_sq_pessoa_pes_pessoa_sq_pessoa',
             'local' => 'sq_pessoa',
             'foreign' => 'sq_pessoa',
             'foreignTable' => 'pes_pessoa',
             ));
        $this->createForeignKey('pes_pessoa_endereco', 'pes_pessoa_endereco_sq_endereco_ger_endereco_sq_endereco', array(
             'name' => 'pes_pessoa_endereco_sq_endereco_ger_endereco_sq_endereco',
             'local' => 'sq_endereco',
             'foreign' => 'sq_endereco',
             'foreignTable' => 'ger_endereco',
             ));
        $this->createForeignKey('pes_pessoa_endereco', 'pes_pessoa_endereco_sq_pessoa_pes_pessoa_sq_pessoa', array(
             'name' => 'pes_pessoa_endereco_sq_pessoa_pes_pessoa_sq_pessoa',
             'local' => 'sq_pessoa',
             'foreign' => 'sq_pessoa',
             'foreignTable' => 'pes_pessoa',
             ));
        $this->createForeignKey('pes_pessoa_fisica', 'pes_pessoa_fisica_sq_municipio_geo_municipio_sq_municipio', array(
             'name' => 'pes_pessoa_fisica_sq_municipio_geo_municipio_sq_municipio',
             'local' => 'sq_municipio',
             'foreign' => 'sq_municipio',
             'foreignTable' => 'geo_municipio',
             ));
        $this->createForeignKey('pes_pessoa_telefone', 'pes_pessoa_telefone_sq_telefone_ger_telefone_sq_telefone', array(
             'name' => 'pes_pessoa_telefone_sq_telefone_ger_telefone_sq_telefone',
             'local' => 'sq_telefone',
             'foreign' => 'sq_telefone',
             'foreignTable' => 'ger_telefone',
             ));
        $this->createForeignKey('pes_pessoa_telefone', 'pes_pessoa_telefone_sq_pessoa_pes_pessoa_sq_pessoa', array(
             'name' => 'pes_pessoa_telefone_sq_pessoa_pes_pessoa_sq_pessoa',
             'local' => 'sq_pessoa',
             'foreign' => 'sq_pessoa',
             'foreignTable' => 'pes_pessoa',
             ));
        $this->createForeignKey('pes_senha', 'pes_senha_sq_pessoa_pes_pessoa_sq_pessoa', array(
             'name' => 'pes_senha_sq_pessoa_pes_pessoa_sq_pessoa',
             'local' => 'sq_pessoa',
             'foreign' => 'sq_pessoa',
             'foreignTable' => 'pes_pessoa',
             ));
        $this->createForeignKey('spe_cargo_emprego', 'scsc', array(
             'name' => 'scsc',
             'local' => 'cd_grup_carg_emprego',
             'foreign' => 'cd_grup_carg_emprego',
             'foreignTable' => 'spe_grupo_cargo_emprego',
             ));
        $this->createForeignKey('spe_servidor', 'spe_servidor_cd_carg_emprego_spe_cargo_emprego_cd_carg_emprego', array(
             'name' => 'spe_servidor_cd_carg_emprego_spe_cargo_emprego_cd_carg_emprego',
             'local' => 'cd_carg_emprego',
             'foreign' => 'cd_carg_emprego',
             'foreignTable' => 'spe_cargo_emprego',
             ));
        $this->createForeignKey('spe_servidor', 'spe_servidor_cd_sit_funcional_spe_sit_funcional_cd_sit_funcional', array(
             'name' => 'spe_servidor_cd_sit_funcional_spe_sit_funcional_cd_sit_funcional',
             'local' => 'cd_sit_funcional',
             'foreign' => 'cd_sit_funcional',
             'foreignTable' => 'spe_sit_funcional',
             ));
        $this->createForeignKey('spe_servidor', 'spe_servidor_cd_ocorrencia_spe_tip_ocorrencia_cd_ocorrencia', array(
             'name' => 'spe_servidor_cd_ocorrencia_spe_tip_ocorrencia_cd_ocorrencia',
             'local' => 'cd_ocorrencia',
             'foreign' => 'cd_ocorrencia',
             'foreignTable' => 'spe_tip_ocorrencia',
             ));
        $this->createForeignKey('spe_servidor', 'scsc_3', array(
             'name' => 'scsc_3',
             'local' => 'cd_tip_escolaridade',
             'foreign' => 'cd_tip_escolaridade',
             'foreignTable' => 'spe_tip_escolaridade',
             ));
        $this->createForeignKey('spe_servidor', 'spe_servidor_cd_tip_formacao_spe_tip_formacao_cd_tip_formacao', array(
             'name' => 'spe_servidor_cd_tip_formacao_spe_tip_formacao_cd_tip_formacao',
             'local' => 'cd_tip_formacao',
             'foreign' => 'cd_tip_formacao',
             'foreignTable' => 'spe_tip_formacao',
             ));
        $this->createForeignKey('spe_servidor', 'spe_servidor_cd_uorg_spe_uorg_cd_uorg', array(
             'name' => 'spe_servidor_cd_uorg_spe_uorg_cd_uorg',
             'local' => 'cd_uorg',
             'foreign' => 'cd_uorg',
             'foreignTable' => 'spe_uorg',
             ));
        $this->createForeignKey('spe_servidor_dados', 'spe_servidor_dados_sg_uf_geo_uf_sg_uf', array(
             'name' => 'spe_servidor_dados_sg_uf_geo_uf_sg_uf',
             'local' => 'sg_uf',
             'foreign' => 'sg_uf',
             'foreignTable' => 'geo_uf',
             ));
        $this->createForeignKey('spe_tip_ocorrencia', 'scsc_5', array(
             'name' => 'scsc_5',
             'local' => 'cd_grup_tip_ocorrencia',
             'foreign' => 'cd_grup_tip_ocorrencia',
             'foreignTable' => 'spe_grup_tip_ocorrencia',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('con_controller', 'con_controller_sq_sistema_con_sistema_sq_sistema');
        $this->dropForeignKey('con_layout', 'con_layout_sq_idioma_layout_con_idioma_layout_sq_idioma_layout');
        $this->dropForeignKey('con_layout', 'con_layout_sq_sistema_con_sistema_sq_sistema');
        $this->dropForeignKey('con_layout', 'con_layout_sq_tema_layout_con_tema_layout_sq_tema_layout');
        $this->dropForeignKey('con_layout', 'con_layout_sq_profissional_ins_profissional_sq_profissional');
        $this->dropForeignKey('con_log', 'con_log_sq_profissional_ins_profissional_sq_profissional');
        $this->dropForeignKey('con_menu', 'con_menu_sq_conteiner_con_conteiner_sq_conteiner');
        $this->dropForeignKey('con_menu_profissional', 'con_menu_profissional_sq_menu_con_menu_sq_menu');
        $this->dropForeignKey('con_menu_profissional', 'csis');
        $this->dropForeignKey('con_perfil_estrutura', 'con_perfil_estrutura_sq_perfil_con_perfil_sq_perfil');
        $this->dropForeignKey('con_perfil_menu', 'con_perfil_menu_sq_menu_con_menu_sq_menu');
        $this->dropForeignKey('con_perfil_menu', 'con_perfil_menu_sq_perfil_con_perfil_sq_perfil');
        $this->dropForeignKey('doc_acompanhar', 'doc_acompanhar_sq_digital_op_doc_digital_op_sq_digital_op');
        $this->dropForeignKey('doc_ass_sinonimo', 'dsds');
        $this->dropForeignKey('doc_ass_sinonimo', 'dsds_1');
        $this->dropForeignKey('doc_classificacao', 'dsds_2');
        $this->dropForeignKey('doc_comentario', 'doc_comentario_sq_digital_op_doc_digital_op_sq_digital_op');
        $this->dropForeignKey('doc_delegacao', 'doc_delegacao_sq_operacao_doc_operacao_sq_operacao');
        $this->dropForeignKey('doc_delegacao', 'doc_delegacao_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz');
        $this->dropForeignKey('doc_delegacao', 'dsps');
        $this->dropForeignKey('doc_despacho', 'doc_despacho_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz');
        $this->dropForeignKey('doc_despacho', 'doc_despacho_sq_pessoa_fisica_pes_pessoa_fisica_sq_pessoa_fisica');
        $this->dropForeignKey('doc_digital_op', 'doc_digital_op_sq_delegacao_doc_delegacao_sq_delegacao');
        $this->dropForeignKey('doc_digital_op', 'doc_digital_op_sq_digital_doc_digital_sq_digital');
        $this->dropForeignKey('doc_digital_op', 'doc_digital_op_sq_digital_pai_doc_documento_sq_digital');
        $this->dropForeignKey('doc_digital_op', 'doc_digital_op_sq_operacao_doc_operacao_sq_operacao');
        $this->dropForeignKey('doc_digital_op', 'doc_digital_op_sq_prioridade_doc_prioridade_sq_prioridade');
        $this->dropForeignKey('doc_digital_op', 'doc_digital_op_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz');
        $this->dropForeignKey('doc_digital_op', 'dsps_1');
        $this->dropForeignKey('doc_documento', 'dsds_6');
        $this->dropForeignKey('doc_documento', 'doc_documento_sq_doc_tipo_doc_tipo_sq_doc_tipo');
        $this->dropForeignKey('doc_grp_tram_organiz', 'dsds_8');
        $this->dropForeignKey('doc_grp_tram_organiz', 'dsis');
        $this->dropForeignKey('doc_imagem', 'doc_imagem_sq_digital_op_doc_digital_op_sq_digital_op');
        $this->dropForeignKey('doc_prazo', 'doc_prazo_sq_digital_op_doc_digital_op_sq_digital_op');
        $this->dropForeignKey('doc_resposta', 'doc_resposta_sq_doc_tipo_doc_tipo_sq_doc_tipo');
        $this->dropForeignKey('doc_resposta', 'doc_resposta_sq_tramite_doc_tramite_sq_tramite');
        $this->dropForeignKey('doc_tramite', 'doc_tramite_sq_despacho_doc_despacho_sq_despacho');
        $this->dropForeignKey('doc_tramite', 'doc_tramite_sq_digital_op_doc_digital_op_sq_digital_op');
        $this->dropForeignKey('doc_tramite', 'doc_tramite_sq_malote_doc_malote_sq_malote');
        $this->dropForeignKey('doc_tramite', 'doc_tramite_cd_opcao_envio_doc_tipo_envio_cd_opcao_envio');
        $this->dropForeignKey('doc_tramite', 'doc_tramite_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz');
        $this->dropForeignKey('doc_tramite', 'doc_tramite_sq_pessoa_fisica_pes_pessoa_fisica_sq_pessoa_fisica');
        $this->dropForeignKey('doc_tramite_organiz', 'dsds_11');
        $this->dropForeignKey('doc_tramite_organiz', 'dsis_1');
        $this->dropForeignKey('geo_municipio', 'geo_municipio_sg_uf_geo_uf_sg_uf');
        $this->dropForeignKey('geo_uf', 'geo_uf_sq_regiao_geo_regiao_sq_regiao');
        $this->dropForeignKey('ger_endereco', 'ger_endereco_sq_municipio_geo_municipio_sq_municipio');
        $this->dropForeignKey('ger_endereco', 'ger_endereco_cd_pais_geo_pais_cd_pais');
        $this->dropForeignKey('ger_telefone', 'ger_telefone_cd_pais_geo_pais_cd_pais');
        $this->dropForeignKey('ger_telefone', 'ger_telefone_sq_tel_tipo_ger_tel_tipo_sq_tel_tipo');
        $this->dropForeignKey('ins_doc_legal', 'isis');
        $this->dropForeignKey('ins_doc_legal', 'ins_doc_legal_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz');
        $this->dropForeignKey('ins_endereco_estrutura', 'ins_endereco_estrutura_sq_endereco_ger_endereco_sq_endereco');
        $this->dropForeignKey('ins_endereco_estrutura', 'ins_endereco_estrutura_sq_estrutura_ins_estrutura_sq_estrutura');
        $this->dropForeignKey('ins_estrutura', 'ins_estrutura_sq_tipo_estrut_ins_tipo_estrut_sq_tipo_estrut');
        $this->dropForeignKey('ins_estrutura', 'ins_estrutura_sq_unid_organiz_ins_unid_organiz_sq_unid_organiz');
        $this->dropForeignKey('ins_prof_lotacao', 'ins_prof_lotacao_sq_cat_cargo_ins_cat_cargo_sq_cat_cargo');
        $this->dropForeignKey('ins_prof_lotacao', 'ins_prof_lotacao_sq_estrutura_ins_estrutura_sq_estrutura');
        $this->dropForeignKey('ins_prof_lotacao', 'isis_2');
        $this->dropForeignKey('ins_prof_senha', 'ins_prof_senha_sq_profissional_ins_profissional_sq_profissional');
        $this->dropForeignKey('ins_profissional', 'ins_profissional_sq_prof_tipo_ins_prof_tipo_sq_prof_tipo');
        $this->dropForeignKey('ins_profissional', 'ins_profissional_cd_matricula_spe_servidor_cd_matricula');
        $this->dropForeignKey('ins_tel_estrutura', 'ins_tel_estrutura_sq_telefone_ger_telefone_sq_telefone');
        $this->dropForeignKey('ins_tel_estrutura', 'ins_tel_estrutura_sq_estrutura_ins_estrutura_sq_estrutura');
        $this->dropForeignKey('ins_unid_organiz', 'ins_unid_organiz_sq_unid_tipo_ins_unid_tipo_sq_unid_tipo');
        $this->dropForeignKey('ins_unid_organiz', 'ins_unid_organiz_cd_uorg_spe_uorg_cd_uorg');
        $this->dropForeignKey('ins_unid_organiz_municipio', 'isgs');
        $this->dropForeignKey('ins_unid_organiz_municipio', 'isis_5');
        $this->dropForeignKey('pes_documento_tipo', 'pes_documento_tipo_cd_tipo_pes_tipo_cd_tipo');
        $this->dropForeignKey('pes_email_pessoa', 'pes_email_pessoa_sq_email_ger_email_sq_email');
        $this->dropForeignKey('pes_email_pessoa', 'pes_email_pessoa_sq_pessoa_pes_pessoa_sq_pessoa');
        $this->dropForeignKey('pes_pessoa', 'pes_pessoa_cd_pais_geo_pais_cd_pais');
        $this->dropForeignKey('pes_pessoa', 'pes_pessoa_cd_tipo_pes_tipo_cd_tipo');
        $this->dropForeignKey('pes_pessoa_documento', 'pes_pessoa_documento_sg_uf_geo_uf_sg_uf');
        $this->dropForeignKey('pes_pessoa_documento', 'psps_1');
        $this->dropForeignKey('pes_pessoa_documento', 'pes_pessoa_documento_sq_pessoa_pes_pessoa_sq_pessoa');
        $this->dropForeignKey('pes_pessoa_endereco', 'pes_pessoa_endereco_sq_endereco_ger_endereco_sq_endereco');
        $this->dropForeignKey('pes_pessoa_endereco', 'pes_pessoa_endereco_sq_pessoa_pes_pessoa_sq_pessoa');
        $this->dropForeignKey('pes_pessoa_fisica', 'pes_pessoa_fisica_sq_municipio_geo_municipio_sq_municipio');
        $this->dropForeignKey('pes_pessoa_telefone', 'pes_pessoa_telefone_sq_telefone_ger_telefone_sq_telefone');
        $this->dropForeignKey('pes_pessoa_telefone', 'pes_pessoa_telefone_sq_pessoa_pes_pessoa_sq_pessoa');
        $this->dropForeignKey('pes_senha', 'pes_senha_sq_pessoa_pes_pessoa_sq_pessoa');
        $this->dropForeignKey('spe_cargo_emprego', 'scsc');
        $this->dropForeignKey('spe_servidor', 'spe_servidor_cd_carg_emprego_spe_cargo_emprego_cd_carg_emprego');
        $this->dropForeignKey('spe_servidor', 'spe_servidor_cd_sit_funcional_spe_sit_funcional_cd_sit_funcional');
        $this->dropForeignKey('spe_servidor', 'spe_servidor_cd_ocorrencia_spe_tip_ocorrencia_cd_ocorrencia');
        $this->dropForeignKey('spe_servidor', 'scsc_3');
        $this->dropForeignKey('spe_servidor', 'spe_servidor_cd_tip_formacao_spe_tip_formacao_cd_tip_formacao');
        $this->dropForeignKey('spe_servidor', 'spe_servidor_cd_uorg_spe_uorg_cd_uorg');
        $this->dropForeignKey('spe_servidor_dados', 'spe_servidor_dados_sg_uf_geo_uf_sg_uf');
        $this->dropForeignKey('spe_tip_ocorrencia', 'scsc_5');
    }
}