<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addgeouf extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('geo_uf', array(
             'sg_uf' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'primary' => true,
              'length' => NULL,
             ),
             'sq_regiao' => 
             array(
              'type' => 'integer',
              'length' => 2,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'cd_uf' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'nm_uf' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sg_uf',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('geo_uf');
    }
}