<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddocasssinonimo extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('doc_ass_sinonimo', array(
             'sq_doc_ass_sinonimo' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_classificacao' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'sq_classif_sinonimo' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_doc_ass_sinonimo',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('doc_ass_sinonimo');
    }
}