<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddocmalote extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('doc_malote', array(
             'sq_malote' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'ds_malote' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_malote',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('doc_malote');
    }
}