<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addinsproflotacao extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ins_prof_lotacao', array(
             'sq_prof_lotacao' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_cat_cargo' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'sq_estrutura' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'sq_prof_supervisor' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
             ),
             'sq_profissional' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'dt_per_inicio' => 
             array(
              'type' => 'date',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => 25,
             ),
             'dt_per_termino' => 
             array(
              'type' => 'date',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => false,
              'primary' => false,
              'length' => 25,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_prof_lotacao',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ins_prof_lotacao');
    }
}