<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addinsenderecoestrutura extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ins_endereco_estrutura', array(
             'sq_endereco_estrutura' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'sq_estrutura' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'sq_endereco' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sq_endereco_estrutura',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ins_endereco_estrutura');
    }
}