<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpestipo extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('pes_tipo', array(
             'cd_tipo' => 
             array(
              'type' => 'string',
              'fixed' => true,
              'unsigned' => false,
              'primary' => true,
              'length' => NULL,
             ),
             'nm_tipo' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'primary' => false,
              'length' => NULL,
             ),
             'st_ativo' => 
             array(
              'type' => 'boolean',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'notnull' => true,
              'default' => 'true',
              'primary' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'cd_tipo',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('pes_tipo');
    }
}