<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headScript();
        ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/extjs/examples/ux/ProgressBarPager.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/extjs/examples/ux/statusbar/StatusBar.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/application/modules/default/views/layouts/index/layout.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/extjs/examples/ux/IconComboBox.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/extjs/examples/ux/RowEditor.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/extjs/examples/ux/Spinner.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/extjs/examples/ux/SpinnerField.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/vtypes/vtypes.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/upload/upload.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/outros/resolucao.js"></script>
    </head>
    <body>
        <div id="introducao"><div id="marca-intro"></div><div id="loader"><p>Carregando...</p></div></div>
        <script type="text/javascript" language="javascript" >
            Ext.onReady(function(){
                try{
                    new App.Default.Layout.Index;
                    Ext.get('introducao').fadeOut(100);
                }catch(e){
                    alert('Ocorreu um erro fatal!\n['+e+']');
                }
            });
        </script>
    </body>
</html>