<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headScript();
        ?>
    </head>
    <body>

    </body>
</html>

<style type="text/css">
    div{
        color: #ccc;
    }
</style>

<div>
    <img alt=""  src="<?php echo SYSTEM_PATH; ?>/public/img/loader.gif"> Aguarde...
</div>